#include "LabelTable.h"

std::string regList[REG_CNT] = {
    "$zero", "$at", "$v0", "$v1", "$a0", "$a1", "$a2", "$a3", 
    "$t0", "$t1", "$t2", "$t3", "$t4", "$t5", "$t6", "$t7",
    "$s0", "$s1", "$s2", "$s3", "$s4", "$s5", "$s6", "$s7",
    "$t8", "$t9", "$k0", "$k1", "$gp", "$sp", "$fp", "$ra"
};

InstTable instTable[INST_TYPE_CNT] = {
    /* R-type instructions */
    {"add", R_TYPE, 0, 0x20, {RD, RS, RT}},
    {"addu", R_TYPE, 0, 0x21, {RD, RS, RT}},
    {"and", R_TYPE, 0, 0x24, {RD, RS, RT}},
    {"div", R_TYPE, 0, 0x1A, {RS, RT, NO_ARG}},
    {"divu", R_TYPE, 0, 0x1B, {RS, RT, NO_ARG}},
    {"jalr", R_TYPE, 0, 0x09, {RD, RS, NO_ARG}},
    {"jr", R_TYPE, 0, 0x08, {RS, NO_ARG, NO_ARG}},
    {"mfhi", R_TYPE, 0, 0x10, {RD, NO_ARG, NO_ARG}},
    {"mflo", R_TYPE, 0, 0x12, {RD, NO_ARG, NO_ARG}},
    {"mthi", R_TYPE, 0, 0x11, {RS, NO_ARG, NO_ARG}},
    {"mtlo", R_TYPE, 0, 0x13, {RS, NO_ARG, NO_ARG}},
    {"mult", R_TYPE, 0, 0x18, {RS, RT, NO_ARG}},
    {"multu", R_TYPE, 0, 0x19, {RS, RT, NO_ARG}},
    {"nor", R_TYPE, 0, 0x27, {RD, RS, RT}},
    {"or", R_TYPE, 0, 0x25, {RD, RS, RT}},
    {"sll", R_TYPE, 0, 0x00, {RD, RT, SA}},
    {"sllv", R_TYPE, 0, 0x04, {RD, RT, RS}},
    {"slt", R_TYPE, 0, 0x2A, {RD, RS, RT}},
    {"sltu", R_TYPE, 0, 0x2B, {RD, RS, RT}},
    {"sra", R_TYPE, 0, 0x03, {RD, RS, SA}},
    {"srav", R_TYPE, 0, 0x07, {RD, RT, RS}},
    {"srl", R_TYPE, 0, 0x02, {RD, RT, SA}},
    {"srlv", R_TYPE, 0, 0x06, {RD, RT, RS}},
    {"sub", R_TYPE, 0, 0x22, {RD, RS, RT}},
    {"subu", R_TYPE, 0, 0x23, {RD, RS, RT}},
    {"syscall", R_TYPE, 0, 0x0C, {NO_ARG, NO_ARG, NO_ARG}},
    {"xor", R_TYPE, 0, 0x26, {RD, RS, RT}},
    /* I-type instructions */
    {"addi", I_TYPE, 0x08, 0, {RT, RS, IMM}},
    {"addiu", I_TYPE, 0x09, 0, {RT, RS, IMM}},
    {"andi", I_TYPE, 0x0C, 0, {RT, RS, IMM}},
    {"beq", I_TYPE, 0x04, 0, {RS, RT, LABEL}},
    {"bgez", I_TYPE, 0x01, 0, {RS, LABEL, NO_ARG}},
    {"bgtz", I_TYPE, 0x07, 0, {RS, LABEL, NO_ARG}},
    {"blez", I_TYPE, 0x06, 0, {RS, LABEL, NO_ARG}},
    {"bltz", I_TYPE, 0x01, 0, {RS, LABEL, NO_ARG}},
    {"bne", I_TYPE, 0x05, 0, {RS, RT, LABEL}},
    {"lb", I_TYPE, 0x20, 0, {RT, IMM_RS, NO_ARG}},
    {"lbu", I_TYPE, 0x24, 0, {RT, IMM_RS, NO_ARG}},
    {"lh", I_TYPE, 0x21, 0, {RT, IMM_RS, NO_ARG}},
    {"lhu", I_TYPE, 0x25, 0, {RT, IMM_RS, NO_ARG}},
    {"lui", I_TYPE, 0x0F, 0, {RT, IMM, NO_ARG}},
    {"lw", I_TYPE, 0x23, 0, {RT, IMM_RS, NO_ARG}},
    {"ori", I_TYPE, 0x0D, 0, {RT, RS, IMM}},
    {"sb", I_TYPE, 0x28, 0, {RT, IMM_RS, NO_ARG}},
    {"slti", I_TYPE, 0x0A, 0, {RT, RS, IMM}},
    {"sltiu", I_TYPE, 0x0B, 0, {RT, RS, IMM}},
    {"sh", I_TYPE, 0x29, 0, {RT, IMM_RS, NO_ARG}},
    {"sw", I_TYPE, 0x2B, 0, {RT, IMM_RS, NO_ARG}},
    {"xori", I_TYPE, 0x0E, 0, {RT, RS, IMM}},
    {"lwl", I_TYPE, 0x22, 0, {RT, IMM_RS, NO_ARG}},
    {"lwr", I_TYPE, 0x26, 0, {RT, IMM_RS, NO_ARG}},
    {"swl", I_TYPE, 0x2A, 0, {RT, IMM_RS, NO_ARG}},
    {"swr", I_TYPE, 0x2E, 0, {RT, IMM_RS, NO_ARG}},
    /* J-type instructions */
    {"j", J_TYPE, 0x02, 0, {LABEL, NO_ARG, NO_ARG}},
    {"jal", J_TYPE, 0x03, 0, {LABEL, NO_ARG, NO_ARG}}
};